import Head from "next/head";
import React, { useState } from "react";
import Navbar from "../Navbar";
import styles from "../../styles/Layout.module.scss";

interface LayoutsProps {}

const Layouts: React.FC<LayoutsProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Shadee Merhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.root}>
        <Navbar />
        <div className={styles.page_container}>{children}</div>
      </div>
    </>
  );
};
export default Layouts;
