import Head from "next/head";
import React, { useState } from "react";
import Navbar from "../Navbar";
import Header from "./Header";
import styles from "../../styles/Layout.module.scss";
import { withApollo } from "../../util/withApollo";

interface LayoutsProps {}

const Layouts: React.FC<LayoutsProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Shadee Merhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.root}>
        <Navbar />
        <div className={styles.page_wrapper}>
          <Header />
          <div className={styles.page_content}>{children}</div>
        </div>
      </div>
    </>
  );
};
export default withApollo({ ssr: true })(Layouts);
