import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

type LayoutsProps = {};

const Layouts: React.FC<LayoutsProps> = () => {
    return (
        <>
            <Head>
                <title>Shadee Merhi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
        </>
    );
};
export default Layouts;
