import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { withApollo } from "../util/withApollo";
import Navbar from "../components/Navbar";

import { useProjectsQuery } from "../generated/graphql";

const Home: NextPage = () => {
    const { data, loading, error } = useProjectsQuery();
    console.log("HERE IS DATA", loading, data);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="main_color">Shadee's Personal Website</div>
        </div>
    );
};

export default withApollo({ ssr: true })(Home);
